version: '3.3'
services:
  pythonapp:
    build: ./python/
    command: sh -c "sleep 50s; python3 ./connect_mysql.py"
    volumes:
      - ./data/:/usr/app/src/data/
    depends_on:
      - mysql
      
  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3313:3313'

